' option + D to preview

@startuml "Lab Tests API"

class Physician {
  +name
  +crm_state
  +crm_number
}

class Patient {
  +name
  +cpf
  +email
  +birth_date
}

class Test {
  +name
  +date
  +result_range
  +result
}

class TestReport {
  +token
}

Patient "1" -- "*" TestReport

Test "1..*" -o "1" TestReport

Test "*" - "1" Patient : "           "

TestReport "*" - "0..1" Physician : "           "
' A physician may ask (a patient to do) many lab tests, which will come together in a test report
' Each test report may have zero or one physician (since sometimes the patient can ask for a test also)

@enduml
